Fix incorrect and missing function prototypes
Examples:

asm6f.c:150:16: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
void initlabels();
               ^
                void

asm6f.c:577:7: error: no previous prototype for function 'my_strupr' [-Werror,-Wmissing-prototypes]
char *my_strupr(char *string)
      ^